name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: mbartsch/lftp
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        imageName: mbartsch/lftp:$SHA8
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
