name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GITSHORT: $(git rev-parse --short HEAD | cut -f 1,8)

    steps:
    - run: export
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: latest,${GITSHORT}
        imageName: mbartsch/lftp
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
