name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - run: echo ::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c 1-8)
      id: vars
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: mbartsch/lftp
        tag: ${{ steps.vars.outputs.sha_short }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        platforms: linux/amd64,linux/arm64
#    - name: Build the Docker image
#      uses: ilteoood/docker_buildx@v1.0.2
#      with:
#        publish: true
#        tag: latest,${{ steps.vars.outputs.sha_short }}
#        imageName: mbartsch/lftp
#        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
#        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
#        platform: linux/amd64,linux/arm64
